/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.pages;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import javax.swing.*;
import org.json.JSONObject;
import rest.RestAPIHook;
import ui.components.Associations.AssociationsFeed;
import ui.components.Associations.AssociationsFeedCell;
import ui.components.Associations.AssociationsFeedTableModel;

/**
 *
 * @author shrut
 */
public final class AdminHomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    private JSONObject inputJSON;

    public AdminHomePage(JSONObject input) {
        //fetching the JSON file which contains information about user loging in.
        //Also initializing the UI components calling the panels to be hidden and visible.
        this.inputJSON = input;
        initComponents();
        active();
    }

    public void allHidden(){
        //Hidding all the panels and only setting the navigation panels to be visible and enabling them.
        navigationPanel.setVisible(true);
        navigationPanel.setEnabled(true);
        homePanel.setVisible(false);
        homePanel.setEnabled(false);
        profilePanel.setVisible(false);
        profilePanel.setEnabled(false);
    }

    public void active() {
        //Hidding all the panels and setting navigation and home panel to be visible.
        allHidden();
        homePanel.setVisible(true);
        homePanel.setEnabled(true);
    }
    
    public void adminHomeTable(){
        //function to fetch and populate the data of approvals for associations.
        String adminUrl = "http://localhost:9001/associations/?type=administrator";
        //initializing the RestAPI an fetching the data as a JSON file.
        RestAPIHook adminHook = new RestAPIHook();
        JSONObject adminData = adminHook.invokeGetMethod(adminUrl);
        //iterating over the JSON file.
        Iterator<String> adminKeys = adminData.keys();
        List adminFeeds = new ArrayList();
        while(adminKeys.hasNext()){
            //continuing id isSuccess parameter is true.
            String adminKey = adminKeys.next();
            if("isSuccess".equals(adminKey)){
                continue;
            }
            //initializing hashmap and populating the data from the JSON.
            HashMap adminTemp = new HashMap();
            adminTemp.put("association_id", adminKey);
            adminTemp.put("isAdmin",true);
            //creating a JSON and appending data to be displayed in the table.
            JSONObject adminVal = adminData.getJSONObject(adminKey);
            Iterator<String> adminChildKeys = adminVal.keys();
            while(adminChildKeys.hasNext()){
                String adminChildKey = adminChildKeys.next();
                adminTemp.put(adminChildKey, adminVal.get(adminChildKey));
            }
            //adding the data to the arraylist to create the table.
            adminFeeds.add(new AssociationsFeed(adminTemp));
        }
        //creating a new Jtable with custom render and editor methods
        adminHomeTable = new JTable(new AssociationsFeedTableModel(adminFeeds));
        adminHomeTable.setDefaultRenderer(AssociationsFeed.class, new AssociationsFeedCell());
        adminHomeTable.setDefaultEditor(AssociationsFeed.class, new AssociationsFeedCell());
        //setting properties for the table
        adminHomeTable.setRowHeight(60);
        adminHomeTable.setModel(adminHomeTable.getModel());
        adminHomeTable.getColumnModel().getColumn(0).setHeaderValue("Home");
        adminHomeTable.getTableHeader().resizeAndRepaint();
        adminHomeTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        adminHomeTable.setFocusable(false);
        adminHomeTable.setOpaque(false);
        adminHomeTable.setRequestFocusEnabled(false);
        adminHomeTable.setRowSelectionAllowed(false);
        adminHomeTable.setSurrendersFocusOnKeystroke(true);
        adminHomeTable.setUpdateSelectionOnSort(false);
        adminHomeTable.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(adminHomeTable);
        //hidding all the panels and only making the home panel visible.
        allHidden();
        homePanel.setVisible(true);
        homePanel.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //defining the UI
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        navigationPanel = new javax.swing.JPanel();
        homeAdminButton = new javax.swing.JButton();
        profileAssocButton1 = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();
        profilePanel = new javax.swing.JPanel();
        userType = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        homePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adminHomeTable = new javax.swing.JTable();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navigationPanel.setBackground(new java.awt.Color(102, 102, 102));

        homeAdminButton.setBackground(new java.awt.Color(102, 102, 102));
        homeAdminButton.setForeground(new java.awt.Color(255, 255, 255));
        homeAdminButton.setText("Home");
        homeAdminButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        homeAdminButton.setMaximumSize(new java.awt.Dimension(140, 29));
        homeAdminButton.setMinimumSize(new java.awt.Dimension(140, 29));
        homeAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeAdminButtonActionPerformed(evt);
            }
        });

        profileAssocButton1.setBackground(new java.awt.Color(102, 102, 102));
        profileAssocButton1.setForeground(new java.awt.Color(255, 255, 255));
        profileAssocButton1.setText("Profile");
        profileAssocButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        profileAssocButton1.setMaximumSize(new java.awt.Dimension(140, 29));
        profileAssocButton1.setMinimumSize(new java.awt.Dimension(140, 29));
        profileAssocButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileAssocButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navigationPanelLayout = new javax.swing.GroupLayout(navigationPanel);
        navigationPanel.setLayout(navigationPanelLayout);
        navigationPanelLayout.setHorizontalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeAdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(profileAssocButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );
        navigationPanelLayout.setVerticalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigationPanelLayout.createSequentialGroup()
                .addComponent(profileAssocButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeAdminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(365, 365, 365))
        );

        jPanel1.add(navigationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 270, 560));

        headerPanel.setBackground(new java.awt.Color(51, 51, 255));

        titleLabel.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("UMASS EVENTS BOARD");

        logoutLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        logoutLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoutLabel.setText("LOG OUT");
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap(625, Short.MAX_VALUE)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(520, 520, 520)
                .addComponent(logoutLabel)
                .addGap(42, 42, 42))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutLabel))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1560, 70));

        userType.setText("User Type :        Admin");

        description.setText("Email :        "+ this.inputJSON.get("email").toString());

        fname.setText("First Name :       "+this.inputJSON.get("first_name").toString());

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(description, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addComponent(fname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(964, Short.MAX_VALUE))
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(userType, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );

        jPanel1.add(profilePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1560, 560));

        adminHomeTable.setModel(adminHomeTable.getModel());
        jScrollPane1.setViewportView(adminHomeTable);
        adminHomeTable();

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jPanel1.add(homePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1560, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        // TODO add your handling code here:
        //disposing the current frame and creating a new login page.
        this.dispose();
        LoginPage newLoginPage = new LoginPage();
        newLoginPage.setExtendedState(JFrame.MAXIMIZED_BOTH);
        newLoginPage.setVisible(true);
    }//GEN-LAST:event_logoutLabelMouseClicked

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuMouseClicked

    private void homeAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeAdminButtonActionPerformed
        // TODO add your handling code here:
        //calling the home table when clicking the home button. 
        adminHomeTable();
    }//GEN-LAST:event_homeAdminButtonActionPerformed

    private void profileAssocButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileAssocButton1ActionPerformed
        // TODO add your handling code here:
        //hidding all the panels and setting the profile panel to visible.
        allHidden();
        profilePanel.setVisible(true);
        profilePanel.setEnabled(true);
    }//GEN-LAST:event_profileAssocButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable adminHomeTable;
    private javax.swing.JLabel description;
    private javax.swing.JLabel fname;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton homeAdminButton;
    public javax.swing.JPanel homePanel;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JPanel navigationPanel;
    private javax.swing.JButton profileAssocButton1;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel userType;
    // End of variables declaration//GEN-END:variables
}
