/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.pages;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.json.JSONObject;
import rest.RestAPIHook;

/**
 *
 * @author shrut
 */
public final class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
 
    //Constructor called on initialization
    public LoginPage() {
        //initializing the UI components.
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //defining the UI
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        LoginPanel = new javax.swing.JPanel();
        useridLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        registerAssoButton = new javax.swing.JButton();
        useridTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JPasswordField();
        LoginTitle = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        registerUserButton = new javax.swing.JButton();
        Border = new javax.swing.JLabel();

        jFrame1.setBackground(new java.awt.Color(255, 255, 255));
        jFrame1.setExtendedState(JFrame.MAXIMIZED_BOTH);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1560, 630));

        headerPanel.setBackground(new java.awt.Color(204, 0, 0));

        titleLabel.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("UMASS EVENTS BOARD");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap(638, Short.MAX_VALUE)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(632, 632, 632))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        LoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        LoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        useridLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        useridLabel.setText("User ID");
        LoginPanel.add(useridLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, -1, -1));

        passwordLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        passwordLabel.setText("Password");
        LoginPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, -1, -1));

        registerAssoButton.setBackground(new java.awt.Color(204, 204, 255));
        registerAssoButton.setText("Register as an Association");
        registerAssoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerAssoButtonActionPerformed(evt);
            }
        });
        LoginPanel.add(registerAssoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 400, 170, 30));
        LoginPanel.add(useridTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, 210, -1));
        LoginPanel.add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 270, 210, -1));

        LoginTitle.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        LoginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginTitle.setText("Login");
        LoginPanel.add(LoginTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 280, 70));

        LoginButton.setBackground(new java.awt.Color(204, 204, 255));
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        LoginPanel.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 330, 100, 40));

        registerUserButton.setBackground(new java.awt.Color(204, 204, 255));
        registerUserButton.setText("Register as a User");
        registerUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerUserButtonActionPerformed(evt);
            }
        });
        LoginPanel.add(registerUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 170, 30));

        Border.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        LoginPanel.add(Border, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 430, 390));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1560, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerAssoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerAssoButtonActionPerformed
        // TODO add your handling code here:
        // disposing the current frame and redirecting to the association regestration page.
        this.dispose();
        RegistrationPageAssociation associationRegisteration = new RegistrationPageAssociation();
        associationRegisteration.setExtendedState(JFrame.MAXIMIZED_BOTH);
        associationRegisteration.setVisible(true);
    }//GEN-LAST:event_registerAssoButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        String userValue = useridTextField.getText();        //get user entered username from the textField1  
        String passValue = passwordTextField.getText();        //get user entered pasword from the textField2 
        // initializing the rest api to validate the login credentials.
        String loginUrl = "http://localhost:9000/users/?user_name=" + userValue + "&password=" + passValue;
        RestAPIHook loginHook = new RestAPIHook();
        //fetching the user data as JSON.
        JSONObject userData = loginHook.invokeGetMethod(loginUrl);

        //check whether the credentials are authenticated or not  
        if(userData.get("isSuccess").toString() == "true") {  //if authentic, navigate user to a new page  
            if(userData.get("user_code").toString().equals("0")) {
                //user_code 0 is for amdin account type.
                // disposing the current frame and redirecting to the admin home page.
                AdminHomePage adminHomePage = new AdminHomePage(userData);
                adminHomePage.setExtendedState(JFrame.MAXIMIZED_BOTH);
                adminHomePage.setVisible(true);
                this.dispose();
            }
            else if (userData.get("user_code").toString().equals("1")) {
                //user_code 1 is for association account type.
                //checking if association user is approved or not.
                //rest call for the above check.
                loginUrl = "http://localhost:9001/associations/?type=single&user_id="+userData.get("user_id").toString();
                JSONObject associationData = loginHook.invokeGetMethod(loginUrl);
                //if association user is not approved throw popup error.
                if(associationData.get("approval_status").equals("N")){
                    JOptionPane.showMessageDialog(jPanel1, "Pending Approval");
                }
                else{
                    // disposing the current frame and redirecting to the association home page.
                    AssociationHomePage associationHomePage = new AssociationHomePage(userData,associationData);
                    associationHomePage.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    associationHomePage.setVisible(true);
                    this.dispose();
                }
            } 
            else if(userData.get("user_code").toString().equals("2")) {
                //user_code 1 is for user account type.
                // disposing the current frame and redirecting to the user home page.
                UserHomePage userHP = new UserHomePage(userData);
                userHP.setExtendedState(JFrame.MAXIMIZED_BOTH);
                userHP.setVisible(true);
                this.dispose();
            }
        } else {
            //show error message  
            JOptionPane.showMessageDialog(jPanel1, "Please enter valid username and password"); 
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void registerUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerUserButtonActionPerformed
        // TODO add your handling code here:
        // disposing the current frame and redirecting to the user regestration page.
        this.dispose();
        RegistrationPageUser userRegistrationPage = new RegistrationPageUser();
        userRegistrationPage.setExtendedState(JFrame.MAXIMIZED_BOTH);
        userRegistrationPage.setVisible(true);
    }//GEN-LAST:event_registerUserButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>
        try {
            //main method to call the login page.
            LoginPage loginpage = new LoginPage();
            loginpage.setExtendedState(JFrame.MAXIMIZED_BOTH);
            loginpage.setVisible(true); //make form visible to the use

        } catch (Exception e) {
            //handle exception   
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Border;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JLabel LoginTitle;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JButton registerAssoButton;
    private javax.swing.JButton registerUserButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel useridLabel;
    private javax.swing.JTextField useridTextField;
    // End of variables declaration//GEN-END:variables
}
