/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.pages;

import java.awt.Color;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.json.JSONObject;
import rest.RestAPIHook;

/**
 *
 * @author shrut
 */
public final class RegistrationPageUser extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
 
    //Constructor to be called on initialization
    public RegistrationPageUser() {
        initComponents();
    }

    //Validate Input Fields
    public boolean validations() {
        boolean isValid = true;
        firstNameTextField.setBackground(Color.white);
        lastNameTextField.setBackground(Color.white);
        userNameTextField.setBackground(Color.white);
        emailTextField.setBackground(Color.white);
        passwordTextField.setBackground(Color.white);
        verifyPasswordTextField.setBackground(Color.white);
        System.out.println(firstNameTextField.getText());
        System.out.println("Hi"+lastNameTextField.getText());
        System.out.println(userNameTextField.getText());
        
        if (firstNameTextField.getText().length() == 0) {
            firstNameTextField.setBackground(Color.red);
            isValid = false;
        }
        if (this.lastNameTextField.getText().length() == 0) {
            lastNameTextField.setBackground(Color.red);
            isValid = false;
        }
        if (this.emailTextField.getText().length() == 0) {
            emailTextField.setBackground(Color.red);
            isValid = false;
        }
        if (this.userNameTextField.getText().length() == 0) {
            userNameTextField.setBackground(Color.red);
            isValid = false;
        }
        if (this.passwordTextField.getText().length() == 0) {
            passwordTextField.setBackground(Color.red);
            isValid = false;
        }
        if (this.verifyPasswordTextField.getText().length() == 0) {
            verifyPasswordTextField.setBackground(Color.red);
            isValid = false;
        }
        //Validate if both Password and Verify Password fields are equal
        if (!this.passwordTextField.getText().equals(this.verifyPasswordTextField.getText())){
            passwordTextField.setBackground(Color.red);
            verifyPasswordTextField.setBackground(Color.red);
            isValid = false;
        }

        return isValid;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //defining the UI
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        backPageLabel = new javax.swing.JLabel();
        registrationPanel = new javax.swing.JPanel();
        verifyPasswordLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        verifyPasswordTextField = new javax.swing.JPasswordField();
        RegistrationTitle = new javax.swing.JLabel();
        RegistrationButton = new javax.swing.JButton();
        firstNameLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        userNameTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JPasswordField();
        firstNameLabel1 = new javax.swing.JLabel();
        firstNameLabel2 = new javax.swing.JLabel();
        firstNameLabel3 = new javax.swing.JLabel();
        firstNameLabel4 = new javax.swing.JLabel();
        firstNameLabel5 = new javax.swing.JLabel();
        firstNameLabel6 = new javax.swing.JLabel();

        jFrame1.setBackground(new java.awt.Color(255, 255, 255));
        jFrame1.setExtendedState(JFrame.MAXIMIZED_BOTH);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel1.setPreferredSize(new java.awt.Dimension(1560, 630));

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));

        titleLabel.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("UMASS EVENTS BOARD");

        backPageLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backPageLabel.setForeground(new java.awt.Color(255, 255, 255));
        backPageLabel.setText("BACK");
        backPageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backPageLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(backPageLabel)
                .addGap(528, 528, 528)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backPageLabel)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        registrationPanel.setBackground(new java.awt.Color(255, 255, 255));
        registrationPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        verifyPasswordLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        verifyPasswordLabel.setText("Verify Password");

        lastNameLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lastNameLabel.setText("Last Name");

        RegistrationTitle.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        RegistrationTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegistrationTitle.setText("USER REGISTRATION");

        RegistrationButton.setBackground(new java.awt.Color(204, 204, 255));
        RegistrationButton.setText("Register");
        RegistrationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrationButtonActionPerformed(evt);
            }
        });

        firstNameLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        firstNameLabel.setText("First Name");

        userNameLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        userNameLabel.setText("User Name");

        emailLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        emailLabel.setText("Email");

        passwordLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        passwordLabel.setText("Password");

        firstNameLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        firstNameLabel1.setForeground(new java.awt.Color(255, 0, 0));
        firstNameLabel1.setText("*");

        firstNameLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        firstNameLabel2.setForeground(new java.awt.Color(255, 0, 0));
        firstNameLabel2.setText("*");

        firstNameLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        firstNameLabel3.setForeground(new java.awt.Color(255, 0, 0));
        firstNameLabel3.setText("*");

        firstNameLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        firstNameLabel4.setForeground(new java.awt.Color(255, 0, 0));
        firstNameLabel4.setText("*");

        firstNameLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        firstNameLabel5.setForeground(new java.awt.Color(255, 0, 0));
        firstNameLabel5.setText("*");

        firstNameLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        firstNameLabel6.setForeground(new java.awt.Color(255, 0, 0));
        firstNameLabel6.setText("*");

        javax.swing.GroupLayout registrationPanelLayout = new javax.swing.GroupLayout(registrationPanel);
        registrationPanel.setLayout(registrationPanelLayout);
        registrationPanelLayout.setHorizontalGroup(
            registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrationPanelLayout.createSequentialGroup()
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrationPanelLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(RegistrationTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registrationPanelLayout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(RegistrationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registrationPanelLayout.createSequentialGroup()
                                .addGap(254, 254, 254)
                                .addComponent(firstNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstNameLabel1)
                                .addGap(32, 32, 32)
                                .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrationPanelLayout.createSequentialGroup()
                                .addGap(205, 205, 205)
                                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrationPanelLayout.createSequentialGroup()
                                        .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(passwordLabel)
                                            .addComponent(emailLabel))
                                        .addGap(52, 52, 52)
                                        .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(passwordTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(emailTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrationPanelLayout.createSequentialGroup()
                                        .addComponent(verifyPasswordLabel)
                                        .addGap(52, 52, 52)
                                        .addComponent(verifyPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registrationPanelLayout.createSequentialGroup()
                            .addGap(243, 243, 243)
                            .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(userNameLabel)
                                .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(firstNameLabel6)
                                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstNameLabel4)
                                    .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(registrationPanelLayout.createSequentialGroup()
                                            .addComponent(firstNameLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(registrationPanelLayout.createSequentialGroup()
                                            .addComponent(firstNameLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(firstNameLabel5))))))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        registrationPanelLayout.setVerticalGroup(
            registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrationPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(RegistrationTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameLabel1))
                .addGap(28, 28, 28)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabel)
                    .addComponent(firstNameLabel2))
                .addGap(29, 29, 29)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameLabel)
                    .addComponent(firstNameLabel3))
                .addGap(28, 28, 28)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameLabel4))
                .addGap(26, 26, 26)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameLabel5))
                .addGap(25, 25, 25)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verifyPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameLabel6)
                    .addComponent(verifyPasswordLabel))
                .addGap(61, 61, 61)
                .addComponent(RegistrationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(registrationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(376, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registrationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Actions to be performed when user click Register button
    private void RegistrationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrationButtonActionPerformed
        //Enter loop if all validations are met
        if (validations()) {
            String username = userNameTextField.getText();
            String password = passwordTextField.getText();
            String firstName = firstNameTextField.getText();
            String lastName = lastNameTextField.getText();
            String email = emailTextField.getText();
            Integer userCode = 2;

            //Create a POST call to insert a new user
            String url = "http://localhost:9000/users/?";
            RestAPIHook a = new RestAPIHook();
            HashMap<String,Object> params = new HashMap<>();
            params.put("user_code", userCode);
            params.put("user_name", username);
            params.put("password", password);
            params.put("first_name", firstName);
            params.put("last_name", lastName);
            params.put("email", email);
            System.out.println(params);
            JSONObject p = a.invokePostMethod(url, params);
            System.out.println(p);
            //Redirect to the Login page if the new user is created
            if(p.get("isSuccess").toString().equals("true")){
                dispose();
                LoginPage login = new LoginPage();
                login.setExtendedState(JFrame.MAXIMIZED_BOTH);
                login.setVisible(true);
            }
            else{
                //Throw error if new user is not created
                JOptionPane.showMessageDialog(registrationPanel, "User name alreay taken", "Error in Registration!", JOptionPane.ERROR_MESSAGE);
                dispose();
                RegistrationPageUser registerLogin = new RegistrationPageUser();
                registerLogin.setExtendedState(JFrame.MAXIMIZED_BOTH);
                registerLogin.setVisible(true);
            }
        }
    }//GEN-LAST:event_RegistrationButtonActionPerformed

    //Redirect to Login Page when BACK is clicked
    private void backPageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backPageLabelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        LoginPage login = new LoginPage();
        login.setVisible(true);
        login.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_backPageLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationPageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>
        try {
            RegistrationPageUser regPage = new RegistrationPageUser();
            regPage.setExtendedState(JFrame.MAXIMIZED_BOTH);
            regPage.setVisible(true); //make form visible to the use

        } catch (Exception e) {
            //handle exception   
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegistrationButton;
    private javax.swing.JLabel RegistrationTitle;
    private javax.swing.JLabel backPageLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel firstNameLabel1;
    private javax.swing.JLabel firstNameLabel2;
    private javax.swing.JLabel firstNameLabel3;
    private javax.swing.JLabel firstNameLabel4;
    private javax.swing.JLabel firstNameLabel5;
    private javax.swing.JLabel firstNameLabel6;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JPanel registrationPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userNameTextField;
    private javax.swing.JLabel verifyPasswordLabel;
    private javax.swing.JTextField verifyPasswordTextField;
    // End of variables declaration//GEN-END:variables
}
